# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R7_Sr7vv8K4sv3pXmvPG7zjQ_MovBVlj
"""

from pycaret.classification import load_model, predict_model
import streamlit as st
import pandas as pd
import numpy as np

model = load_model('Light_GBM')

def predict_quality(model, df):
    predictions_data = predict_model(estimator = model, data = df)
    predictions = predictions_df['Label'][0]
    return predictions

st.title('Prediciting Vehicle Insurance in Customers Web App')
st.write('This is a web app to predicting whether existing customers interested or not based on\
         several features that you can see in the sidebar. Please adjust the\
         value of each feature. After that, click on the Predict button at the bottom to\
         see the prediction.')

Gender = st.sidebar.selectbox('Gender', ['Female', 'Male'])

Age = st.sidebar.number_input('Input your age', min_value=24, max_value=85, value=35)

drive = {0: "No", 1: "Yes"}

def format_func(option):
    return drive[option]

Driving_License = st.sidebar.selectbox("Do you have a driving license?", options=list(drive.keys()), format_func=format_func)

Region_Code = st.sidebar.number_input('Input your region code', min_value=1, max_value=51, value=10)

Vehicle_Age = st.sidebar.selectbox('Input your vehicle age', ['> 2 Years', '1-2 Year', '< 1 Year'])

Vehicle_Damage = st.sidebar.selectbox('Do you have vehicle damage', ['No', 'Yes'])

Annual_Premium = st.sidebar.number_input('Input your annual premium', min_value=2630, max_value=540165, value=30000)

Policy_Sales_Channel = st.sidebar.number_input('Input your policy sales channel', min_value=1, max_value=163, value=30)

Vintage = st.sidebar.number_input('How long you have been a our customers (in a day)', min_value=10, max_value=299, value=30)

features = {'Gender': Gender, 'Age': Age,
            'Driving_License': Driving_License, 'Region_Code': Region_Code,
            'Vehicle_Age': Vehicle_Age, 'Vehicle_Damage': Vehicle_Damage,
            'Annual_Premium ':Annual_Premium, 'Policy_Sales_Channel': Policy_Sales_Channel,
            'Vintage': Vintage
            }

features_df  = pd.DataFrame([features])

st.table(features_df)

if st.button('Predict'):
    prediction = predict_quality(model, features_df)
    st.write(' Based on feature values, your'+ str(prediction))
